name: GitHub Actions Demo
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]
    
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: prepare environment
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}

    - name: install requirements
      run: |
        pip3 install pytest setuptools
        pip3 install -r requirements.txt
        
    - name: run test
      run: |
        python3 -m pytest tests

    - name: build wheels
      run: |
        python3 setup.py sdist bdist_wheel
        twine upload --repository-url https://test.pypi.org/legacy/ dist/*
